// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/my-shows.ts";
import * as $1 from "./routes/find/[search].tsx";
import * as $2 from "./routes/find/index.tsx";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/playing.tsx";
import * as $5 from "./routes/today.tsx";
import * as $$0 from "./islands/Play.tsx";
import * as $$1 from "./islands/SearchBox.tsx";
import * as $$2 from "./islands/TVShow.tsx";

const manifest = {
  routes: {
    "./routes/api/my-shows.ts": $0,
    "./routes/find/[search].tsx": $1,
    "./routes/find/index.tsx": $2,
    "./routes/index.tsx": $3,
    "./routes/playing.tsx": $4,
    "./routes/today.tsx": $5,
  },
  islands: {
    "./islands/Play.tsx": $$0,
    "./islands/SearchBox.tsx": $$1,
    "./islands/TVShow.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
